<a href="https://colab.research.google.com/github/Dohyeok-Oh/github-slideshow/blob/master/numpy_1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list = [[1,2,3],[4,5,6],[7,8,9]]

arr = np.array(list)
a = arr[0:2, 0:2]
print(a)

[[1 2]
 [4 5]]


In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.add(a,b)
print(c) 

[5 7 9]


In [ ]:
list1 = [[1,2], [3,4]]
list2 = [[5,6], [7,8]]

a = np.array(list1)
b = np.array(list2)

product = np.dot(a,b)

print(product)


[[19 22]
 [43 50]]


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
s = np.sum(a)
print(s)

c = np.sum(a, axis=1)
print(c)


10
[3 7]
